apiVersion: v1
kind: Pod
metadata:
  name: gem-scheduler
spec:
  hostNetwork: true
  containers:
  - name: gem-scheduler
    image: gcr.io/google_containers/gem-scheduler:34d0b8f8b31e27937327961528739bc9
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/gem-scheduler --master=127.0.0.1:8080 --v=2 --leader-elect=true 1>>/var/log/gem-scheduler.log
      2>&1
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /var/log/gem-scheduler.log
      name: logfile
    - mountPath: /var/run/secrets/gemin.io/serviceaccount
      name: default-token-s8ejd
      readOnly: true
  volumes:
  - hostPath:
      path: /var/log/gem-scheduler.log
    name: logfile
