apiVersion: v1
kind: Service
metadata:
  name: gem-dns
  namespace: gem-system
  labels:
    gem-app: gem-dns
    gemin.io/cluster-service: "true"
    gemin.io/name: "GemDNS"
spec:
  selector:
    gem-app: gem-dns
  clusterIP: 10.16.0.3
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
