apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
spec:
  containers:
  - name: gemini-serve-hostname
    image: gcr.io/google_containers/serve_hostname
    resources:
      limits:
        cpu: "3"
        memory: 100Mi
